#!/usr/bin/env node
// PixelLab streaming generator for The Paladin's Revelation.
//
// Usage:
//   PIXELLAB_API_KEY=xxx node pipeline/generate.mjs            # generate everything missing
//   PIXELLAB_API_KEY=xxx node pipeline/generate.mjs scenes     # one group only
//   PIXELLAB_API_KEY=xxx node pipeline/generate.mjs --keys chapel,sword
//   PIXELLAB_API_KEY=xxx node pipeline/generate.mjs --force    # regenerate even if status says done
//
// Streams: queues all jobs in parallel, then polls every 8s, downloading PNGs
// into ../assets/ as soon as each one finishes. status.json is rewritten on
// every state change so a crashed run resumes cleanly.

import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { upscaleOne } from "./upscale-one.mjs";

const __dirname  = path.dirname(fileURLToPath(import.meta.url));
const ROOT       = path.resolve(__dirname, "..");
const ASSET_DIR  = path.join(ROOT, "assets");
const MANIFEST   = path.join(__dirname, "manifest.json");
const STATUS     = path.join(__dirname, "status.json");
const API        = "https://api.pixellab.ai/v1";
const KEY        = process.env.PIXELLAB_API_KEY;
const POLL_MS    = 8000;
const STYLE_TAIL = " — dark fantasy 1987 Mac/Amiga adventure pixel art, limited palette, heavy blacks, painterly Shadowgate style";

if (!KEY) { console.error("Set PIXELLAB_API_KEY"); process.exit(1); }

const args     = process.argv.slice(2);
const force    = args.includes("--force");
const keysArg  = args.find(a => a.startsWith("--keys="));
const onlyKeys = keysArg ? new Set(keysArg.slice(7).split(",")) : null;
const groups   = args.filter(a => !a.startsWith("--"));

const headers = { "Authorization": `Bearer ${KEY}`, "Content-Type": "application/json" };

const readJson  = async p => JSON.parse(await fs.readFile(p, "utf8"));
const writeJson = async (p, v) => fs.writeFile(p, JSON.stringify(v, null, 2));

async function api(method, path, body) {
  const r = await fetch(API + path, { method, headers, body: body && JSON.stringify(body) });
  if (!r.ok) throw new Error(`${method} ${path} → ${r.status} ${await r.text()}`);
  return r.json();
}

async function download(url, dest) {
  const r = await fetch(url);
  if (!r.ok) throw new Error(`download ${url} → ${r.status}`);
  await fs.writeFile(dest, Buffer.from(await r.arrayBuffer()));
}

function flatten(manifest) {
  const out = [];
  for (const [group, list] of Object.entries(manifest.assets)) {
    if (groups.length && !groups.includes(group)) continue;
    for (const a of list) {
      if (onlyKeys && !onlyKeys.has(a.key)) continue;
      out.push({ ...a, group });
    }
  }
  return out;
}

async function queue(asset) {
  const description = asset.description + STYLE_TAIL;
  if (asset.type === "character") {
    return api("POST", "/characters", {
      description, name: asset.name, mode: asset.mode || "standard",
      n_directions: asset.n_directions || 4, view: asset.view, size: asset.size,
      body_type: asset.body_type || "humanoid", template: asset.template
    });
  }
  return api("POST", "/objects", {
    description, directions: asset.directions || 1, view: asset.view,
    size: asset.size, n_frames: asset.n_frames || 1
  });
}

async function check(asset, id) {
  const ep = asset.type === "character" ? `/characters/${id}` : `/objects/${id}`;
  return api("GET", ep);
}

function pickUrl(asset, info) {
  if (asset.type === "character") {
    const r = info.rotations || info.directions || [];
    return r[0]?.image_url || r[0]?.url || info.preview_url;
  }
  return info.frames?.[0]?.image_url || info.rotations?.[0]?.image_url || info.image_url || info.preview_url;
}

async function upscale(asset, srcPath) {
  const dest = await upscaleOne(asset.key, srcPath);
  return path.relative(ROOT, dest);
}

async function emitBrowserManifest(status) {
  const completed = Object.entries(status.assets)
    .filter(([, v]) => v.status === "completed")
    .map(([k]) => k);
  const hd = Object.entries(status.assets)
    .filter(([, v]) => v.status === "completed" && v.hd)
    .map(([k]) => k);
  const js = `// auto-generated by pipeline/generate.mjs\nwindow.PIXELLAB_ASSETS = ${JSON.stringify(completed)};\nwindow.PIXELLAB_HD = ${JSON.stringify(hd)};\n`;
  await fs.writeFile(path.join(ASSET_DIR, "manifest.js"), js);
}

async function main() {
  await fs.mkdir(ASSET_DIR, { recursive: true });
  const manifest = await readJson(MANIFEST);
  const status   = await readJson(STATUS).catch(() => ({ assets: {} }));
  const assets   = flatten(manifest);

  console.log(`Pipeline: ${assets.length} asset(s) in scope.`);

  // Queue
  for (const a of assets) {
    const cur = status.assets[a.key];
    if (!force && cur?.status === "completed") { console.log(`✓ skip ${a.key} (done)`); continue; }
    if (cur?.status === "queued" || cur?.status === "processing") { console.log(`↻ resume ${a.key} (${cur.id})`); continue; }
    try {
      const res = await queue(a);
      const id  = res.id || res.character_id || res.object_id;
      status.assets[a.key] = { id, type: a.type, status: "queued", queued_at: new Date().toISOString() };
      await writeJson(STATUS, status);
      console.log(`→ queued ${a.key} (${id})`);
    } catch (e) {
      console.error(`✗ queue ${a.key}: ${e.message}`);
      status.assets[a.key] = { status: "failed", error: e.message };
      await writeJson(STATUS, status);
    }
  }

  // Poll
  const pending = () => assets.filter(a => {
    const s = status.assets[a.key]?.status;
    return s === "queued" || s === "processing";
  });

  while (pending().length) {
    await new Promise(r => setTimeout(r, POLL_MS));
    for (const a of pending()) {
      const rec = status.assets[a.key];
      try {
        const info = await check(a, rec.id);
        if (info.status === "completed") {
          const url = pickUrl(a, info);
          if (!url) throw new Error("no image url in response");
          const file = path.join(ASSET_DIR, `${a.key}.png`);
          await download(url, file);
          const hd = await upscale(a, file).catch(e => { console.error(`upscale ${a.key}: ${e.message}`); return null; });
          status.assets[a.key] = { ...rec, status: "completed", file: path.relative(ROOT, file), hd, completed_at: new Date().toISOString() };
          await writeJson(STATUS, status);
          await emitBrowserManifest(status);
          console.log(`✓ ${a.key} → assets/${a.key}.png`);
        } else if (info.status === "failed") {
          status.assets[a.key] = { ...rec, status: "failed", error: info.error || "unknown" };
          await writeJson(STATUS, status);
          console.error(`✗ ${a.key}: ${info.error}`);
        } else {
          if (rec.status !== info.status) {
            status.assets[a.key] = { ...rec, status: info.status };
            await writeJson(STATUS, status);
          }
          process.stdout.write(`. ${a.key}(${info.progress ?? "?"}%) `);
        }
      } catch (e) {
        console.error(`\npoll ${a.key}: ${e.message}`);
      }
    }
  }

  const done   = assets.filter(a => status.assets[a.key]?.status === "completed").length;
  const failed = assets.filter(a => status.assets[a.key]?.status === "failed").length;
  console.log(`\nDone. ${done}/${assets.length} completed${failed ? `, ${failed} failed` : ""}.`);
}

main().catch(e => { console.error(e); process.exit(1); });
