// One-shot batch upscaler: process every assets/<key>.png that lacks @hd.png.
// Pass --force to regenerate all.
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { upscaleOne } from "./upscale-one.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT      = path.resolve(__dirname, "..");
const ASSET_DIR = path.join(ROOT, "assets");
const force     = process.argv.includes("--force");

const all = await fs.readdir(ASSET_DIR);
const sources = all.filter(f => f.endsWith(".png") && !f.includes("@hd"));
const haveHd  = new Set(all.filter(f => f.includes("@hd.png")).map(f => f.replace("@hd.png", "")));

const completed = [];
for (const f of sources) {
  const key = f.replace(/\.png$/, "");
  if (!force && haveHd.has(key)) { completed.push(key); console.log(`= skip ${key}`); continue; }
  const dst = await upscaleOne(key, path.join(ASSET_DIR, f));
  completed.push(key);
  console.log(`✓ ${key} -> ${path.basename(dst)}`);
}

// PIXELLAB_ASSETS = every base PNG on disk (so renderer can swap any of them in).
const allKeys = sources.map(f => f.replace(/\.png$/, "")).sort();
const manifest = path.join(ASSET_DIR, "manifest.js");
await fs.writeFile(manifest,
  `// auto-generated by pipeline\nwindow.PIXELLAB_ASSETS = ${JSON.stringify(allKeys)};\nwindow.PIXELLAB_HD = ${JSON.stringify(completed)};\n`);
console.log(`\nDone. ${completed.length} HD assets total.`);
